name: Get MSIX Package
on:
  workflow_dispatch:

jobs:
  packaging:
    name: Get files
    runs-on: windows-2022
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-files
          run-id: 12406176708
          github-token: ${{ secrets.GH_PAT }}
          repository: iljukhaput/starc
          
      - name: Install MSVC 2022
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
        
      #- name: Packaging
      #  run: makeappx.exe pack /d . /p starc-package.msix

      - name: Cope images
        run: |
          mkdir -p Images
          ROOT_DIR="../../"
          EXE_APP_DIR="."
          cp $ROOT_DIR/Images/StoreLogo.scale-400.png $EXE_APP_DIR/Images
          cp $ROOT_DIR/Images/Square150x150Logo.scale-400.png $EXE_APP_DIR/Images
          cp $ROOT_DIR/Images/Square44x44Logo.scale-400.png $EXE_APP_DIR/Images
          cp $ROOT_DIR/Images/Wide310x150Logo.scale-400.png $EXE_APP_DIR/Images
          cp $ROOT_DIR/Images/SplashScreen.scale-400.png $EXE_APP_DIR/Images
          cp $ROOT_DIR/Images/SmallTile.scale-400.png $EXE_APP_DIR/Images
          cp $ROOT_DIR/Images/LargeTile.scale-400.png $EXE_APP_DIR/Images
          cp $ROOT_DIR/AppxManifest.xml $EXE_APP_DIR
          
      - name: Display structure of downloaded files
        run: |
          ls -R
          
      - name: Build MSIX package
        run: |
            $env:PATH = $env:PATH + ";C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64"
            makeappx.exe pack /d . /p starc-package.msix

      - name: upload package
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: starc-package.msix

      - name: Get build files
        uses: actions/download-artifact@v4
        with:
          name: package
