name: Show artifacts
on:
  workflow_dispatch:

jobs:
  show:
    name: Get files
    runs-on: windows-2022
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-files
          run-id: 12406176708
          github-token: ${{ secrets.GH_PAT }}
          repository: iljukhaput/starc

      - name: move artifacts
        run: |
          mkdir artifacts
          mv ./!(artifacts) ./artifacts
          
      - name: Display structure of downloaded files
        run: |
          ls -R
          
